<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Accounts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>32a133f7-6d79-4971-b6cf-f71b0b5d6912</testSuiteGuid>
   <testCaseLink>
      <guid>ddefc2af-a8df-42a2-a3a2-8c7246c2d69b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Accounts/TC_102_Invalid Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde29886-2a5b-482e-ae02-716284616459</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8823a82e-441e-4279-a648-6d3f9b9fd1f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbad439a-5ee9-42e1-9ae3-49f8fd489287</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c31e4d9-ee89-4c9f-9be2-887f0bc2b2e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Accounts/TC_103_Import Alert</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
