<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Administration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4fd01f10-370d-4407-a804-cc10b9f1e686</testSuiteGuid>
   <testCaseLink>
      <guid>8e6166ed-59a9-476b-ad3a-aaf2cbf3503b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Administration/TC_006_Change Email Address Negative</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9d80c8c2-3899-4842-89bd-8860d9c6e714</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Administration/TC_005_Error Massege For Numerix in PW</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>768a8863-d09a-4feb-8981-6fb8e631b60c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861bf764-8fd4-47ba-8841-97232cdf94c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>388fd3aa-4b62-4719-a4f4-328327225d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>625e70b3-31b8-4b72-830e-b0d68bef6af7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
