<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParticipantName_column</name>
   <tag></tag>
   <elementGuidId>842714ba-bee8-4fdf-b432-8ee04aeee3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='participant_tbl']/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='participant_tbl']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='participant_tbl']/tbody/tr/td[4]</value>
   </webElementProperties>
</WebElementEntity>
