<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>allColumns</name>
   <tag></tag>
   <elementGuidId>c26eb664-7fcf-4b53-9607-812c289d73d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/thead/tr/th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/thead/tr/th</value>
   </webElementProperties>
</WebElementEntity>
