<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column2</name>
   <tag></tag>
   <elementGuidId>903802b3-6bce-4d5f-9dc5-dec85abb8128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[3]</value>
   </webElementXpaths>
</WebElementEntity>
