<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>column1</name>
   <tag></tag>
   <elementGuidId>3b5e5c38-026d-453b-a4c7-dc2033588aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[2]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@class=&quot;dataTable&quot;][1]/table[1]/tbody/tr/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
