<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Payment And Transfer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>06e2499c-554e-491c-95f9-717379502108</testSuiteGuid>
   <testCaseLink>
      <guid>b5519a6b-bdd6-4116-ae0f-1a69be69dd3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_201_Payment option is clickable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>41147aa4-7934-4889-834d-0a9caf66b33a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_202_ Navigate to Confirmation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bb50e8c-cf16-4b63-a91b-1b9cd13cd79e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4b0c48-8e85-4d5c-92ed-db615317ad49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76f4b193-509d-4c59-9f78-d660951425e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2e9b0de-bcbd-4527-9ffb-f65b3bda3707</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97926035-b3c5-493b-a069-caf3c1de7e69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_203_Dollar Sign Populated</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c983c1eb-9273-4db4-8b1e-d8c6c532d2e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c73542-51a5-4d4d-9c7b-4306c9f047eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d889d439-3baf-44f6-99bd-d8e6ca3facdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d18cd1b-c653-4474-a066-618406341a43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>779d0773-b908-487a-b23f-1d093607fc7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_204_Participant Linked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>201960ce-e509-48d5-9b31-71b627377a52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>684adde0-a473-4ac8-a759-1708d6fbdb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e202edfe-ac0a-4ca5-9e06-4ee3f4f77187</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d040719-9a73-4564-a55f-33dcea2da275</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_205_Pop -Up With Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab211a70-ee70-4ba0-a371-d37366d5eae6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22a12b72-dc3d-449e-b353-de147f43037b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b4877e9-cc0c-4e04-8051-a188106ceba5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de38c515-a003-43e9-9d1f-99c01c7da7f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>369a87be-361b-490c-8cbf-798153404055</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment And Transfer/TC_206_No Of Chars n TempName Field</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
